### ISSUE TITLE
Script stopped working with specific username

### ISSUE THREAD

**Issue by rivy751** [KishanBagaria/dAbot#15]
I've been using this for giving llamas for a while and it was working fine, but now it throws me the following error:

> Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\dAbot.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\dAbot\dAbot.py", line 817, in main
    init()
  File "c:\python27\lib\site-packages\dAbot\dAbot.py", line 677, in init
    load_data()
  File "c:\python27\lib\site-packages\dAbot\dAbot.py", line 598, in load_data
    LlamaTransactions = read_llama_transactions()
  File "c:\python27\lib\site-packages\dAbot\dAbot.py", line 571, in read_llama_transactions
    return set(json.load(f))
  File "c:\python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "c:\python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 221152 (char 221151)
Press any key to exit...

The error happens only when I enter my username. I tried typing different usernames and in those cases the script works fine again, it just throws the "wrong password" error which is to be expected. It isn't a problem after logging in either because if I type my username with a wrong password, it crashes again before even trying to log in. I can run the script properly in another computer too (same internet IP), so I'd guess it's not something from deviantart but an issue with the script.

I've tried reinstalling Python and the script again but that doesn't fix it either. Any idea what could the issue be?

**Comment by jukesama** [comment]
i have had this problem before it has nothing to do with the wrong passwords or passwords in general it has something to do with the way the bot reads the saved llama transactions something dosent line up i guess in the file its saved to

i solved this by editing the function

`def read_llama_transactions():
    if os.path.isfile(LLAMA_TRANSACTIONS_PATH):
        with bz2.BZ2File(LLAMA_TRANSACTIONS_PATH, 'r') as f:
            return set(json.load(f))
    return set()`

to

`def read_llama_transactions():
    try:
        if os.path.isfile(LLAMA_TRANSACTIONS_PATH):
            with bz2.BZ2File(LLAMA_TRANSACTIONS_PATH, 'r') as f:
                return set(json.load(f))
    except Exception as er:
        sys.exc_info()
        # print (sys.exc_traceback)
        print(er)
        traceback.print_exc()
    return set()`

just so it dosent break the bot and it should overwrite the file this is a weird fix that i dont really understand but this has worked for me in the past 
i might look into why this happens so i can expand my understanding.. or maybe KishanBagaria can give some more info but that fix should work just to make it not crash you could also probably delete the 

'.json.bz2' at the LLAMA_TRANSACTIONS_PATH
that is some where in the c drive

**Comment by HetaLilla** [comment]
I had the same problem.
jukesama's solution of deleting the [username].json.bz2 file worked for me.
You can probably find the file at C:\Users\Your name\.dAbot\LlamaTransactions
