### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by jedaj666** [KishanBagaria/dAbot#4]
Hi!
Today i have this problem:
I reinstaling python, dabot and trying on another machine. Thanks for help.

Traceback (most recent call last):
  File "d:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27\Scripts\dAbot.exe\__main__.py", line 9, in <module>
  File "d:\python27\lib\site-packages\dAbot\dAbot.py", line 811, in main
    init()
  File "d:\python27\lib\site-packages\dAbot\dAbot.py", line 671, in init
    load_data()
  File "d:\python27\lib\site-packages\dAbot\dAbot.py", line 594, in load_data
    LlamaTransactions = read_llama_transactions()
  File "d:\python27\lib\site-packages\dAbot\dAbot.py", line 567, in read_llama_transactions
    return set(json.load(f))
  File "d:\python27\lib\json\__init__.py", line 287, in load
    return loads(fp.read(),
EOFError: compressed file ended before the logical end-of-stream was detected

**Comment by jedaj666** [comment]
Problem FIXED - we must delete folder .dabot from User Directory
