### ISSUE TITLE
Llamas to group members

### ISSUE THREAD

**Issue by jedaj666** [KishanBagaria/dAbot#6]
When i try send lama to group_members:

Traceback (most recent call last):
  File "d:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27\Scripts\dAbot.exe\__main__.py", line 9, in <module>
  File "d:\python27\lib\site-packages\dAbot\dAbot.py", line 812, in main
    run()
  File "d:\python27\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "d:\python27\lib\site-packages\retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "d:\python27\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "d:\python27\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "d:\python27\lib\site-packages\dAbot\dAbot.py", line 710, in run
    for m in get_group_members(args['<group>'], args['--reversed']):
  File "d:\python27\lib\site-packages\dAbot\dAbot.py", line 459, in get_group_members
    end_offset     = int(re.search(regex['group_last_offset'], html).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
Press any key to exit...

**Comment by KishanBagaria** [comment]
Which group is that? Try another one, it may work.
